### ISSUE TITLE
ms-Grid-col doesn't render adjacent?

### ISSUE THREAD

**Issue by msimecek** [OfficeDev/office-ui-fabric-core#1123]
I'm using Fabric Core from CDN (v9.6.0) and whatever I try, the columns in `ms-Grid` render **below** one another, not next to each other. I've copy&pasted the [sample from docs](https://developer.microsoft.com/en-us/fabric#/styles/layout) and it doesn't work either. Am I doing domething wrong or is it a bug in Fabric?

HTML:

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Test</title>
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.0/css/fabric.min.css">
</head>

<body class="ms-Fabric">
    <div class="ms-Grid">
        <div class="ms-Grid-row">
            <div class="ms-Grid-col ms-sm6 ms-md4 ms-lg2">A</div>
            <div class="ms-Grid-col ms-sm6 ms-md8 ms-lg10">B</div>
        </div>
    </div>
</body>

</html>
```

And result (with borders for clarity):

![2018-06-27_13-28-57](https://user-images.githubusercontent.com/9624293/41971264-155cd79e-7a0e-11e8-92da-4f6ac3dd50a0.png)
*Edge*

![2018-06-27_13-26-04](https://user-images.githubusercontent.com/9624293/41971180-d165d39c-7a0d-11e8-83f5-fee59fb50bd6.png)
*Firefox*

**Comment by mikewheaton** [comment]
Can you use the developer tools to inspect the styles that are being applied? I copied your code into a CodePen and it looks to be working fine: https://codepen.io/mikewheaton/pen/mKzzeK

**Comment by msimecek** [comment]
@mikewheaton Your CodePen works fine on my machine too. I don't see any difference in code... I even added jQuery and Fabric jQuery plugin to match your CodePen fully and it still doesn't work... You can see for yourself: https://dxfabrictest.azurewebsites.net/

These are the styles for A:

```css
.ms-lg2 {
    width: 16.666666666666664%;
}
.ms-Grid-col {
    position: relative;
    min-height: 1px;
    padding-left: 8px;
    padding-right: 8px;
    box-sizing: border-box;
}
.ms-Fabric {
    color: #333;
    font-family: "Segoe UI Web (West European)",Segoe UI,-apple-system,BlinkMacSystemFont,Roboto,Helvetica Neue,sans-serif;
    font-size: 14px;
}
```

This is B:

```css
.ms-lg10 {
    width: 83.33333333333334%;
}
.ms-Grid-col {
    position: relative;
    min-height: 1px;
    padding-left: 8px;
    padding-right: 8px;
    box-sizing: border-box;
}
.ms-Fabric {
    color: #333;
    font-family: "Segoe UI Web (West European)",Segoe UI,-apple-system,BlinkMacSystemFont,Roboto,Helvetica Neue,sans-serif;
    font-size: 14px;
}
```
