### ISSUE TITLE
Directionality mixins don't work by default?

### ISSUE THREAD

**Issue by sabintim** [OfficeDev/office-ui-fabric-core#1223]
Looks like the some of the LTR mixins in the following file don't work by default?
(e.g., when there is no dir="ltr" attribute in the DOM explicitly).

Should LTR be treated as default if the attribute is absent?

https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/mixins/_Directionality.Mixins.scss

```css
// This one will produce LTR margins by default even when dir="..." is not present in the page
@mixin ms-margin($top, $right, $bottom, $left) {
  margin: $top $right $bottom $left;

  @include ms-RTL {
    margin: $top $left $bottom $right;
  }
}

// This one will not produce any margin if dir="..." is not explicitly specified in page
@mixin ms-margin-left($distance) {
  @include ms-LTR {
    margin-left: $distance;
  }

  @include ms-RTL {
    margin-right: $distance;
  }
}
```
