### ISSUE TITLE
Move focus mixin from fabric-react to fabric-core.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-core#853]
From https://github.com/OfficeDev/office-ui-fabric-react/issues/417

"Sometimes in our project we want to use the focus-border mixin in fileoffice-ui-fabric-react/src/common/_focusBorder.scss. Could you consider ship it out?"

**Comment by lijunle** [comment]
Another improvement on the `focusBorder` mixin:

The [current implementation](https://github.com/OfficeDev/office-ui-fabric-react/blob/b99a5cfa9b3bcb00520f95a639c8cc5181d29381/src/common/_focusBorder.scss#L17) has a limitation that, the `.ms-Fabric.is-focusVisible` needs to be the *parent* of the `&` element. However, it is a common case that, the `.ms-Fabric.is-focusVisible` is *on the first* of `&` element.

It means, the following code does not work as expected:

```jsx
<Fabric className="container">
  <div className="row">
    <button></button>
  </div>
</Fabric>
```

```scss
.container {
  .row {
    button {
      @focus-border();
    }
  }
}
```

Because it produces:

```css
.ms-Fabric.is-focusVisible .container .row button:focus:after { ... }
```

Notice the space between `.ms-Fabric.is-focusVisible` and `.container`.

It could be great to produce such CSS to make the above structure works:

```css
.container.ms-Fabric.is-focusVisible .row button:focus:after { ... }
```

I made an attempt with SassScript with the following prototype:

```scss
@function slice($list,$start,$end:null){
    $newlist:();
    $end:if($end==null,length($list),$end); 
    @for $i from $start through $end{ $newlist:append($newlist,nth($list,$i));};
    @return $newlist;
}

@mixin focus-border() {
  @each $parent in & {
    $first: nth($parent, 1);
    $rest: slice($parent, 1);
    @at-root (with: media) {
      .helper #{$first} #{$rest}:focus:after
      #{$first}.helper #{$rest}:focus:after {
        border: none;
      }
    }
  }
}

.container {
  position: relative;
  outline: none;

  .row {
    button, li, a, img {
      @include focus-border();
    }
  }
}
```

If you think it is good, I could like to send a PR here.
